# Generated by Django 5.1.3 on 2024-11-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SpyCat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("years_of_experience", models.PositiveIntegerField()),
                ("breed", models.CharField()),
                ("salary", models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
